# Generated by Django 3.0.1 on 2019-12-27 12:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=30)),
                ('person_address', models.CharField(max_length=100)),
                ('person_contact', models.CharField(max_length=50)),
                ('person_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_description', models.CharField(max_length=100)),
                ('solution_ok', models.BooleanField()),
                ('solution_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 12, 27, 13, 24, 28, 534690))),
                ('record_id', models.IntegerField()),
                ('device_info', models.CharField(max_length=50)),
                ('device_adds', models.CharField(max_length=50)),
                ('device_error', models.CharField(max_length=100)),
                ('person_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Person')),
                ('servis_solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.Solution')),
            ],
        ),
    ]
