# Generated by Django 3.0.1 on 2019-12-27 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='device_adds',
        ),
        migrations.AddField(
            model_name='record',
            name='device_type',
            field=models.CharField(choices=[('NTB', 'Notebook'), ('PC', 'Computer'), ('SMP', 'SmartPhone'), ('TBL', 'Tablet'), ('OT', 'Other')], default='NON', max_length=4),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 13, 32, 45, 880462)),
        ),
    ]
