# Generated by Django 3.0.1 on 2019-12-30 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
                ('material_info', models.CharField(max_length=50)),
                ('material_type', models.CharField(choices=[('NEW', 'New material'), ('REPAS', 'Repas material'), ('SOFT', 'Software material'), ('OTHER', 'Other material')], default='NON', max_length=5)),
                ('material_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='record',
            old_name='device_error',
            new_name='device_problem',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_contact',
        ),
        migrations.RemoveField(
            model_name='record',
            name='device_adds',
        ),
        migrations.RemoveField(
            model_name='record',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='solution_ok',
        ),
        migrations.AddField(
            model_name='person',
            name='person_email',
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='device_type',
            field=models.CharField(choices=[('NTB', 'Notebook'), ('PC', 'Computer'), ('SMP', 'SmartPhone'), ('TBL', 'Tablet'), ('OT', 'Other')], default='NON', max_length=4),
        ),
        migrations.AddField(
            model_name='record',
            name='solution_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_time',
            field=models.TimeField(default='00:05:00'),
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_type',
            field=models.CharField(choices=[('HW_REP', 'Hardware Repair'), ('HW_CHG', 'Hardware Change'), ('SW_RES', 'Software Reinstall'), ('SW_REP', 'Software Repair'), ('OTHER', 'Other repair')], default='NON', max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='person_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Person'),
        ),
        migrations.AlterField(
            model_name='record',
            name='servis_solution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='records.Solution'),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 19, 26, 38, 226349)),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_materials',
            field=models.ManyToManyField(default=None, to='records.Material'),
        ),
    ]
