# Generated by Django 3.0.1 on 2020-01-01 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20191230_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 17, 27, 28, 775890)),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_time',
            field=models.TimeField(default='01:00:00'),
        ),
    ]
