# Generated by Django 3.0.1 on 2020-01-01 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200101_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 17, 59, 47, 510654)),
        ),
    ]
