# Generated by Django 3.0.1 on 2020-01-01 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20200101_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 19, 36, 15, 92953)),
        ),
    ]
