# Generated by Django 3.0.1 on 2020-01-07 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20200101_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 12, 34, 39, 899118)),
        ),
    ]
