# Generated by Django 3.0.1 on 2019-12-27 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20191227_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_date',
            field=models.DateTimeField(default=datetime.date(2019, 12, 27)),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.IntegerField(default=1577464346.305928),
        ),
    ]
