# Generated by Django 3.0.1 on 2019-12-27 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20191227_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='record_id',
        ),
        migrations.AlterField(
            model_name='person',
            name='person_phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 17, 55, 55, 60827)),
        ),
    ]
