# Generated by Django 3.0.1 on 2019-12-27 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20191227_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 18, 39, 56, 297208)),
        ),
    ]
