# Generated by Django 3.0.1 on 2019-12-28 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20191227_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
                ('material_info', models.CharField(max_length=50)),
                ('material_type', models.CharField(choices=[('NEW', 'New material'), ('REPAS', 'Repas material'), ('OTHER', 'Other material')], default='NON', max_length=5)),
                ('material_cost', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='person_contact',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 12, 16, 24, 250023)),
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_materials',
            field=models.ManyToManyField(to='records.Materials'),
        ),
    ]
