# Generated by Django 3.0.1 on 2019-12-28 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_auto_20191228_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='device_error',
            new_name='device_problem',
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 14, 15, 0, 354841)),
        ),
    ]
