# Generated by Django 3.0.1 on 2019-12-28 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_auto_20191228_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('NEW', 'New material'), ('REPAS', 'Repas material'), ('SOFT', 'Software material'), ('OTHER', 'Other material')], default='NON', max_length=5),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 14, 27, 24, 368376)),
        ),
    ]
